export const STATIONS = [
  "Times Sq-42 St", "Grand Central-42 St", "34 St-Herald Sq", "14 St-Union Sq",
  "Fulton St", "Jay St-MetroTech", "Atlantic Av-Barclays Ctr", "125 St",
  "59 St-Columbus Circle", "72 St", "86 St", "96 St", "103 St", "110 St",
  "116 St", "135 St", "145 St", "155 St", "168 St", "175 St", "181 St",
  "190 St", "207 St", "215 St", "Inwood-207 St", "200 St", "Dyckman St",
  "Canal St", "Chambers St", "Cortlandt St", "Rector St", "South Ferry",
  "Wall St", "Bowling Green", "Borough Hall", "Hoyt St", "Nevins St",
  "Bergen St", "Grand Army Plaza", "Eastern Pkwy-Brooklyn Museum",
  "Franklin Ave", "Crown Hts-Utica Ave", "Sutter Ave-Rutland Rd",
  "Saratoga Ave", "Rockaway Ave", "Junius St", "Pennsylvania Ave",
  "Van Siclen Ave", "Cleveland St", "Norwood Ave", "Liberty Ave",
  "Aqueduct Racetrack", "Aqueduct-N Conduit Ave", "Howard Beach-JFK Airport",
  "Broad Channel", "Far Rockaway-Mott Ave", "Rockaway Park-Beach 116 St",
  "Beach 105 St", "Beach 98 St", "Beach 90 St", "Beach 67 St",
  "Beach 60 St", "Beach 44 St", "Beach 36 St", "Beach 25 St",
  "Astoria-Ditmars Blvd", "Astoria Blvd", "30 Ave", "Broadway",
  "36 Ave", "39 Ave", "Queensboro Plaza", "Court Sq", "21 St-Queensbridge",
  "Long Island City-Queens Plaza", "23 St-Ely Ave", "45 St", "46 St",
  "Jackson Hts-Roosevelt Ave", "74 St-Broadway", "82 St-Jackson Hts",
  "90 St-Elmhurst Ave", "95 St", "Junction Blvd", "103 St-Corona Plaza",
  "111 St", "Mets-Willets Point", "Main St-Flushing", "Jamaica-179 St",
  "Jamaica Center-Parsons/Archer", "Jamaica-Van Wyck", "Sutphin Blvd",
  "Briarwood", "Kew Gardens-Union Tpke", "75 Ave", "Forest Hills-71 Ave",
  "67 Ave", "63 Dr-Rego Park", "Woodhaven Blvd", "Grand Ave-Newtown",
  "Elmhurst Ave", "Jackson Hts-Roosevelt Ave", "65 St", "Northern Blvd",
  "46 St-Bliss St", "Steinway St", "36 St", "33 St", "Queensboro Plaza",
  "Prospect Ave", "25 St", "Bay Ridge Ave", "77 St", "86 St",
  "Bay Ridge-95 St", "4 Ave-9 St", "Smith-9 Sts", "Carroll St",
  "Clinton-Washington Aves", "Nostrand Ave", "Kingston-Throop Aves",
  "Myrtle-Willoughby Aves", "Gates Ave", "Halsey St", "Kosciuszko St",
  "Myrtle Ave", "DeKalb Ave", "Hewes St", "Lorimer St", "Metropolitan Ave",
  "Grand St", "Flushing Ave", "Jefferson St", "Wilson Ave", "Bushwick Ave",
  "Ralph Ave", "Shepherd Ave", "Broadway Junction", "Atlantic Ave",
  "Lefferts Blvd", "Euclid Ave", "Pitkin Ave", "Canarsie-Rockaway Pkwy",
  "E 105 St", "New Lots Ave", "Livonia Ave", "Brownsville",
  "Chauncey St", "Halsey St", "Gates Ave", "Kosciuszko St",
  "DeKalb Ave", "Nassau Ave", "Graham Ave", "Lorimer St",
  "Union Ave", "Montrose Ave", "Grand St", "Hewes St",
  "Marcy Ave", "Essex St", "Delancey St", "2 Ave", "Bleecker St",
  "Broadway-Lafayette St", "Spring St", "Prince St", "8 St-NYU",
  "14 St", "23 St", "28 St", "33 St", "42 St-Bryant Park",
  "47-50 Sts-Rockefeller Ctr", "49 St", "57 St", "5 Ave-53 St",
  "Lexington Ave-53 St", "51 St", "59 St", "68 St-Hunter College",
  "77 St", "86 St", "96 St", "103 St", "110 St", "116 St",
  "125 St", "137 St-City College", "145 St", "157 St", "168 St",
  "175 St", "181 St", "191 St", "Dyckman St", "207 St",
  "Marble Hill-225 St", "231 St", "238 St", "Van Cortlandt Park-242 St",
  "Woodlawn", "Mosholu Pkwy", "Bedford Park Blvd", "Kingsbridge Rd",
  "Fordham Rd", "183 St", "Burnside Ave", "176 St", "170 St",
  "167 St", "161 St-Yankee Stadium", "149 St-Grand Concourse",
  "138 St-Grand Concourse", "125 St", "3 Ave-149 St", "Freeman St",
  "Simpson St", "Intervale Ave", "Prospect Ave", "Jackson Ave",
  "Cypress Ave", "E 143 St-St Mary's St", "Longwood Ave",
  "E 149 St", "Brook Ave", "Hunts Point Ave", "Whitlock Ave",
  "Elder Ave", "Morrison Ave-Soundview", "St Lawrence Ave",
  "Parkchester", "Castle Hill Ave", "Zerega Ave", "Westchester Sq",
  "Middletown Rd", "Buhre Ave", "Pelham Bay Park",
  "Pelham Pkwy", "Morris Park", "Bronxdale", "Allerton Ave",
  "Gun Hill Rd", "Burke Ave", "Nereid Ave", "233 St",
  "225 St", "219 St", "Gun Hill Rd", "Baychester Ave",
  "Co-op City", "Eastchester-Dyre Ave",
  "Wakefield-241 St", "Nereid Ave", "Burke Ave",
  "Coney Island-Stillwell Ave", "Bay Pkwy", "25 Ave",
  "Bay 50 St", "Ocean Pkwy", "Brighton Beach", "Ocean Ave",
  "Sheepshead Bay", "Neck Rd", "Gravesend-86 St", "Kings Hwy",
  "Avenue U", "Avenue X", "Neptune Ave",
  "W 8 St-NY Aquarium", "Stillwell Ave",
  "Avenue H", "Avenue J", "Avenue M", "Avenue N", "Avenue P",
  "Avenue U", "Kings Hwy", "Beverly Rd",
  "Cortelyou Rd", "Newkirk Ave", "Church Ave", "Beverley Rd",
  "Prospect Park", "15 St-Prospect Park", "Fort Hamilton Pkwy",
  "9 Ave", "New Utrecht Ave", "18 Ave", "20 Ave",
  "Bay Pkwy", "55 St", "50 St",
  "8 Ave", "Borough Park", "53 St", "55 St",
  "Fort Hamilton Pkwy", "9 Ave",
  "High St", "Clark St", "Court St", "Bergen St",
  "7 Ave", "15 St-Prospect Park", "Windsor Ter",
  "Ditmas Ave", "18 Ave", "Avenue I",
  "Bay Pkwy", "Avenue N", "Avenue P", "Avenue U",
  "Kings Hwy", "Avenue X", "Avenue Z",
  "Coney Island-Stillwell Ave",
  "St George", "Tompkinsville", "Stapleton", "Clifton",
  "Grasmere", "Old Town", "Dongan Hills", "Jefferson Ave",
  "Grant City", "New Dorp", "Oakwood Heights", "Bay Terrace",
  "Great Kills", "Eltingville", "Annadale", "Huguenot",
  "Prince's Bay", "Pleasant Plains", "Richmond Valley",
  "Arthur Kill", "Tottenville",
].sort()